---
deployment:
  tasks:
    - export DEPLOYPATH=/home/davidcve/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp/css style.css $DEPLOYPATH
    - /bin/cp/assets images $DEPLOYPATH
    - /bin/cp/js js $DEPLOYPATH
